apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-factorial-app
  namespace: factorial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: factorial-app
  template:
    metadata:
      labels:
        app: factorial-app
    spec:
      containers:
        - name: factorial
          image: diversim90/factorial-app-for-k8s:0.0.1

# kubectl apply -f factorial-app-deploy1.yaml
# kubectl -n factorial get pods
# kubectl -n factorial describe pod pid-id