spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        encrypt:
          enabled: false
server:
  port: 8080

logging:
  level:
    root: info
    org.msa.configserver: debug
