spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        encrypt:
          enabled: false
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ # Docker에서 Eureka 서버와 통신
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: info
    org.msa.configserver: debug
