apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: ku
spec:
  rules:
    - http:
        paths:
          #path 로 요청이 들어오면, 해당 요청을 지정된 backend 로 보내도록 하는 설정
          - pathType: Prefix
            path: /         #해당 경로로 들어오는 요청을 gateway-service로 라우팅함.
            backend:
              service:
                name: gateway-server
                port:
                  number: 8090
    - host: eureka.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: eureka-server
                port:
                  number: 8761