spring:
  application:
    name: item-service
  datasource:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:tcp://h2-database:1521/test # Docker 네트워크 상의 H2 데이터베이스 URL
    url: jdbc:mysql://mysql-service:3306/itemdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/ # Eureka Server Docker 네트워크 경로
      defaultZone: http://eureka-server.ku.svc.cluster.local:8761/

logging:
  file:
    name: logs/item-service.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.item: debug
