apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-server
spec:
  type: ClusterIP  # 내부 클러스터에서만 접근 가능
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 8080  # Gateway 서비스 포트
      targetPort: 8080
