spring:
  application:
    name: eureka-server
  profiles:
    active: docker
  #    activate:
  #      on-profile: docker
  cloud:
    config:
      uri: http://config-server:8888
    loadbalancer:
      ribbon:
        enabled: false